### ISSUE TITLE
Error loading script: remove_bg.py in latest sd webui?

### ISSUE THREAD

**Issue by gillbates** [graemeniedermayer/clothseg#6]
Hi @graemeniedermayer 

thx for all the efforts there.

so far, my sd will shows following error on start after installation

```
Python 3.10.0 (default, Aug 27 2023, 13:35:08) [GCC 12.3.0]
Version: v1.6.0
```

```
This extension has been automatically deactivated
Please remove this extension
==========================================================================

*** Error loading script: remove_bg.py
    Traceback (most recent call last):
      File "/home/xxx/servers/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/xxx/servers/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/xxx/servers/stable-diffusion-webui/extensions/clothseg/scripts/remove_bg.py", line 19, in <module>
        from rembg import remove, new_session
    ModuleNotFoundError: No module named 'rembg'

---
```

even I've executed 
```
pip install rem_bg
```

successfully, it still cannot load, any ideas why?

thx in advance!

**Comment by graemeniedermayer** [comment]
this is a little surprising.

Sometimes pip is linked with python2 or a different version of python3

`python3.10 -m pip install rem_bg` 

might work.
